CATEGORIES: list[tuple[str, str]] = [
    ("restaurants", "Restaurants"),
    ("huts", "Mountain Huts"),
    ("bars", "Bars & Nightlife"),
    ("hotels", "Hotels"),
    ("doctors", "Doctors"),
    ("pharmacies", "Pharmacies"),
    ("supermarkets", "Supermarkets"),
    ("shopping", "Shopping"),
    ("banks", "Banks & ATMs"),
    ("leisure", "Leisure"),
]

CATEGORY_TAGS: dict[str, list[tuple[str, str]]] = {
    "restaurants": [
        ("amenity", "restaurant"),
        ("amenity", "cafe"),
        ("amenity", "fast_food"),
    ],
    "huts": [
        ("tourism", "alpine_hut"),
        ("tourism", "wilderness_hut"),
        ("amenity", "shelter"),
    ],
    "bars": [
        ("amenity", "bar"),
        ("amenity", "pub"),
        ("amenity", "nightclub"),
        ("amenity", "biergarten"),
    ],
    "hotels": [
        ("tourism", "hotel"),
        ("tourism", "hostel"),
        ("tourism", "guest_house"),
        ("tourism", "motel"),
    ],
    "doctors": [
        ("amenity", "doctors"),
        ("amenity", "clinic"),
        ("healthcare", "doctor"),
    ],
    "pharmacies": [
        ("amenity", "pharmacy"),
    ],
    "supermarkets": [
        ("shop", "supermarket"),
        ("shop", "convenience"),
        ("shop", "alcohol"),
        ("shop", "bakery"),
        ("shop", "beverages"),
        ("shop", "brewing_supplies"),
        ("shop", "butcher"),
        ("shop", "cheese"),
        ("shop", "chocolate"),
        ("shop", "coffee"),
        ("shop", "confectionery"),
        ("shop", "dairy"),
        ("shop", "deli"),
        ("shop", "farm"),
        ("shop", "food"),
        ("shop", "frozen_food"),
        ("shop", "greengrocer"),
        ("shop", "health_food"),
        ("shop", "ice_cream"),
        ("shop", "nuts"),
        ("shop", "organic"),
        ("shop", "pasta"),
        ("shop", "pastry"),
        ("shop", "seafood"),
        ("shop", "spices"),
        ("shop", "tea"),
        ("shop", "tobacco"),
        ("shop", "tortilla"),
        ("shop", "water"),
        ("shop", "wine"),
    ],
    "shopping": [
        # general
        ("shop", "department_store"),
        ("shop", "general"),
        ("shop", "kiosk"),
        ("shop", "mall"),
        ("shop", "variety_store"),
        ("shop", "wholesale"),
        ("shop", "second_hand"),
        ("shop", "charity"),
        # clothing & accessories
        ("shop", "baby_goods"),
        ("shop", "bag"),
        ("shop", "boutique"),
        ("shop", "clothes"),
        ("shop", "fabric"),
        ("shop", "fashion"),
        ("shop", "fashion_accessories"),
        ("shop", "jewelry"),
        ("shop", "leather"),
        ("shop", "sewing"),
        ("shop", "shoes"),
        ("shop", "tailor"),
        ("shop", "watches"),
        ("shop", "wool"),
        # health & beauty
        ("shop", "beauty"),
        ("shop", "chemist"),
        ("shop", "cosmetics"),
        ("shop", "hearing_aids"),
        ("shop", "herbalist"),
        ("shop", "medical_supply"),
        ("shop", "nutrition_supplements"),
        ("shop", "optician"),
        ("shop", "perfumery"),
        # hardware & home improvement
        ("shop", "bathroom_furnishing"),
        ("shop", "country_store"),
        ("shop", "doityourself"),
        ("shop", "electrical"),
        ("shop", "fireplace"),
        ("shop", "garden_centre"),
        ("shop", "garden_furniture"),
        ("shop", "hardware"),
        ("shop", "houseware"),
        ("shop", "paint"),
        ("shop", "pottery"),
        ("shop", "security"),
        # furniture & interior
        ("shop", "antiques"),
        ("shop", "bed"),
        ("shop", "candles"),
        ("shop", "carpet"),
        ("shop", "curtain"),
        ("shop", "doors"),
        ("shop", "flooring"),
        ("shop", "furniture"),
        ("shop", "household_linen"),
        ("shop", "interior_decoration"),
        ("shop", "kitchen"),
        ("shop", "lighting"),
        ("shop", "tiles"),
        # electronics
        ("shop", "computer"),
        ("shop", "electronics"),
        ("shop", "hifi"),
        ("shop", "mobile_phone"),
        ("shop", "printer_ink"),
        # outdoors & sports
        ("shop", "bicycle"),
        ("shop", "fishing"),
        ("shop", "florist"),
        ("shop", "golf"),
        ("shop", "hunting"),
        ("shop", "military_surplus"),
        ("shop", "outdoor"),
        ("shop", "ski"),
        ("shop", "sports"),
        ("shop", "surf"),
        # art, music & hobbies
        ("shop", "art"),
        ("shop", "camera"),
        ("shop", "collector"),
        ("shop", "craft"),
        ("shop", "frame"),
        ("shop", "games"),
        ("shop", "model"),
        ("shop", "music"),
        ("shop", "musical_instrument"),
        ("shop", "photo"),
        ("shop", "trophy"),
        ("shop", "video"),
        ("shop", "video_games"),
        # books, gifts & stationery
        ("shop", "anime"),
        ("shop", "books"),
        ("shop", "gift"),
        ("shop", "lottery"),
        ("shop", "newsagent"),
        ("shop", "stationery"),
        ("shop", "toys"),
        # pets
        ("shop", "pet"),
    ],
    "banks": [
        ("amenity", "bank"),
        ("amenity", "atm"),
    ],
    "leisure": [
        ("leisure", "park"),
        ("leisure", "swimming_pool"),
        ("leisure", "water_park"),
        ("amenity", "public_bath"),
        ("leisure", "sports_centre"),
        ("leisure", "fitness_centre"),
        ("leisure", "tennis"),
        ("leisure", "playground"),
        ("amenity", "theatre"),
        ("amenity", "cinema"),
        ("tourism", "museum"),
    ],
}

_COMMON_COLUMNS: list[tuple[str, str]] = [
    ("name", "Name"),
    ("addr:street", "Street"),
    ("addr:housenumber", "No."),
    ("phone", "Phone"),
    ("website", "Website"),
    ("opening_hours", "Opening Hours"),
]

_EXTRA_COLUMNS: dict[str, list[tuple[str, str]]] = {
    "restaurants": [("cuisine", "Cuisine")],
    "huts": [("ele", "Elevation (m)")],
    "hotels": [("stars", "Stars"), ("rooms", "Rooms")],
    "doctors": [("healthcare:speciality", "Speciality")],
    "banks": [("operator", "Operator")],
    "leisure": [("access", "Access")],
}


def get_columns(category: str) -> list[tuple[str, str]]:
    return _COMMON_COLUMNS + _EXTRA_COLUMNS.get(category, [])
